export const PROTOCOL = "vox-chatgpt/1";
export const STORAGE_KEY = "autoChatGPTImages.runtime.v1";
export const SETTINGS_KEY = "autoChatGPTImages.settings.v1";
export const LOG_KEY = "autoChatGPTImages.logs.v1";
export const ALARM_NAME = "auto-chatgpt-images:reconcile";
export const GEMINI_ORIGIN = "https://gemini.google.com";

export const TASK_STATES = Object.freeze({
  QUEUED: "queued",
  CLAIMING: "claiming",
  UPLOADING: "uploading_references",
  SUBMITTING: "submitting",
  WAITING: "waiting",
  COLLECTING: "collecting",
  RETURNING: "returning",
  COMPLETED: "completed",
  FAILED: "failed",
  PAUSED: "paused",
  CANCELED: "canceled"
});

export const ERROR_CODES = Object.freeze({
  UNSUPPORTED_PROTOCOL: "UNSUPPORTED_PROTOCOL",
  VOX_UNREACHABLE: "VOX_UNREACHABLE",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  VERIFICATION_REQUIRED: "VERIFICATION_REQUIRED",
  USAGE_LIMIT_REACHED: "USAGE_LIMIT_REACHED",
  CLAIM_CONFLICT: "CLAIM_CONFLICT",
  REFERENCE_FETCH_FAILED: "REFERENCE_FETCH_FAILED",
  REFERENCE_UPLOAD_FAILED: "REFERENCE_UPLOAD_FAILED",
  REFERENCE_VERIFICATION_FAILED: "REFERENCE_VERIFICATION_FAILED",
  GEMINI_UI_UNSUPPORTED: "GEMINI_UI_UNSUPPORTED",
  SUBMISSION_AMBIGUOUS: "SUBMISSION_AMBIGUOUS",
  SUBMISSION_REJECTED: "SUBMISSION_REJECTED",
  GENERATION_FAILED: "GENERATION_FAILED",
  GENERATION_TIMEOUT: "GENERATION_TIMEOUT",
  RESULT_NOT_NEW: "RESULT_NOT_NEW",
  RESULT_FETCH_FAILED: "RESULT_FETCH_FAILED",
  RESULT_INVALID: "RESULT_INVALID",
  RESULT_CONFLICT: "RESULT_CONFLICT",
  RESULT_SAVE_UNCONFIRMED: "RESULT_SAVE_UNCONFIRMED",
  TASK_CANCELED: "TASK_CANCELED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
});
